"""
Mode Router — R240-5 Minimal Wrapper
=====================================
在现有路由逻辑不改变的前提下，统一生成 ModeDecision metadata。

约束（绝对禁止改变）：
- 任何 M01 / M04 / RTCM / DeerFlow 的实际路由行为
- 任何现有 API 响应结构
- 任何 Governance actual/predicted 语义

设计原则：只包装，不抢权。ModeDecision 是 metadata，不是执行引擎。
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Selected Mode Enum — matches R240-2 ModeDecision.schema.json
# ---------------------------------------------------------------------------

class SelectedMode(StrEnum):
    SEARCH = "search"
    TASK = "task"
    WORKFLOW = "workflow"
    AUTONOMOUS_AGENT = "autonomous_agent"
    ROUNDTABLE = "roundtable"
    DIRECT_ANSWER = "direct_answer"
    CLARIFICATION = "clarification"
    GOVERNANCE_REVIEW = "governance_review"
    MIXED_MODE = "mixed_mode"


class DelegatedTo(StrEnum):
    M01_ORCHESTRATOR = "m01_orchestrator"
    M04_COORDINATOR = "m04_coordinator"
    DEERFLOW_HARNESS = "deerflow_harness"
    PYTHON_GATEWAY = "python_gateway"
    RTCM_MAIN_AGENT_HANDOFF = "rtcm_main_agent_handoff"
    GOVERNANCE_BRIDGE = "governance_bridge"
    FRONTEND_ONLY = "frontend_only"
    CHANNEL_MANAGER = "channel_manager"
    NONE = "none"


# ---------------------------------------------------------------------------
# Delegation defaults — from R240-2 ModePriorityRules.json
# ---------------------------------------------------------------------------

_DELEGATION_DEFAULTS: dict[SelectedMode, DelegatedTo] = {
    SelectedMode.SEARCH: DelegatedTo.M04_COORDINATOR,
    SelectedMode.TASK: DelegatedTo.M04_COORDINATOR,
    SelectedMode.WORKFLOW: DelegatedTo.M04_COORDINATOR,
    SelectedMode.AUTONOMOUS_AGENT: DelegatedTo.DEERFLOW_HARNESS,
    SelectedMode.ROUNDTABLE: DelegatedTo.RTCM_MAIN_AGENT_HANDOFF,
    SelectedMode.DIRECT_ANSWER: DelegatedTo.M01_ORCHESTRATOR,
    SelectedMode.CLARIFICATION: DelegatedTo.M01_ORCHESTRATOR,
    SelectedMode.GOVERNANCE_REVIEW: DelegatedTo.GOVERNANCE_BRIDGE,
    SelectedMode.MIXED_MODE: DelegatedTo.M01_ORCHESTRATOR,
}


# ---------------------------------------------------------------------------
# Candidate Mode record
# ---------------------------------------------------------------------------

@dataclass
class CandidateMode:
    mode: SelectedMode
    confidence: float  # 0.0–1.0
    reason: str


# ---------------------------------------------------------------------------
# State Scope — minimal view scoped to ModeDecision
# ---------------------------------------------------------------------------

@dataclass
class ModeStateScope:
    thread_id: str | None = None
    session_id: str | None = None
    task_id: str | None = None
    workflow_id: str | None = None
    rtcm_session_id: str | None = None
    governance_trace_id: str | None = None
    memory_scope: str = "session"


# ---------------------------------------------------------------------------
# Result Sink — minimal view scoped to ModeDecision
# ---------------------------------------------------------------------------

@dataclass
class ModeResultSink:
    frontend_thread: bool = True
    memory: bool = False
    asset: bool = False
    governance: bool = False
    runtime_artifact: bool = True
    nightly_review: bool = False


# ---------------------------------------------------------------------------
# ModeDecision — R240-5 minimal wrapper
# ---------------------------------------------------------------------------

@dataclass
class ModeDecision:
    """
    ModeDecision metadata — generated by rule-based heuristic.

    All fields optional/defaulted to keep backward compatibility.
    Does NOT change any existing routing/execution logic.
    """
    mode_decision_id: str | None = None
    request_id: str | None = None
    context_id: str | None = None
    selected_mode: SelectedMode = SelectedMode.DIRECT_ANSWER
    candidate_modes: list[CandidateMode] = field(default_factory=list)
    confidence: float = 0.5
    decision_reason: str = ""
    priority_rule_applied: str = ""
    needs_clarification: bool = False
    delegated_to: DelegatedTo = DelegatedTo.NONE
    fallback_mode: SelectedMode | None = None
    allowed_tools: list[str] = field(default_factory=list)
    denied_tools: list[str] = field(default_factory=list)
    state_scope: ModeStateScope = field(default_factory=ModeStateScope)
    result_sink: ModeResultSink = field(default_factory=ModeResultSink)
    created_at: str | None = None
    source_system: str = "gateway"

    def to_dict(self) -> dict[str, Any]:
        return {
            "mode_decision_id": self.mode_decision_id,
            "request_id": self.request_id,
            "context_id": self.context_id,
            "selected_mode": self.selected_mode.value if isinstance(self.selected_mode, SelectedMode) else self.selected_mode,
            "candidate_modes": [
                {"mode": c.mode.value, "confidence": c.confidence, "reason": c.reason}
                for c in self.candidate_modes
            ],
            "confidence": self.confidence,
            "decision_reason": self.decision_reason,
            "priority_rule_applied": self.priority_rule_applied,
            "needs_clarification": self.needs_clarification,
            "delegated_to": self.delegated_to.value if isinstance(self.delegated_to, DelegatedTo) else self.delegated_to,
            "fallback_mode": self.fallback_mode.value if isinstance(self.fallback_mode, SelectedMode) else self.fallback_mode,
            "allowed_tools": self.allowed_tools,
            "denied_tools": self.denied_tools,
            "state_scope": {
                "thread_id": self.state_scope.thread_id,
                "session_id": self.state_scope.session_id,
                "task_id": self.state_scope.task_id,
                "workflow_id": self.state_scope.workflow_id,
                "rtcm_session_id": self.state_scope.rtcm_session_id,
                "governance_trace_id": self.state_scope.governance_trace_id,
                "memory_scope": self.state_scope.memory_scope,
            },
            "result_sink": {
                "frontend_thread": self.result_sink.frontend_thread,
                "memory": self.result_sink.memory,
                "asset": self.result_sink.asset,
                "governance": self.result_sink.governance,
                "runtime_artifact": self.result_sink.runtime_artifact,
                "nightly_review": self.result_sink.nightly_review,
            },
            "created_at": self.created_at,
            "source_system": self.source_system,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ModeDecision:
        if data is None:
            return cls()
        known = {}
        for key in [
            "mode_decision_id", "request_id", "context_id", "selected_mode",
            "confidence", "decision_reason", "priority_rule_applied",
            "needs_clarification", "delegated_to", "fallback_mode",
            "allowed_tools", "denied_tools", "created_at", "source_system",
        ]:
            if key in data:
                known[key] = data[key]

        # Parse enums
        if "selected_mode" in known and isinstance(known["selected_mode"], str):
            try:
                known["selected_mode"] = SelectedMode(known["selected_mode"])
            except ValueError:
                known["selected_mode"] = SelectedMode.DIRECT_ANSWER
        if "delegated_to" in known and isinstance(known["delegated_to"], str):
            try:
                known["delegated_to"] = DelegatedTo(known["delegated_to"])
            except ValueError:
                known["delegated_to"] = DelegatedTo.NONE
        if "fallback_mode" in known and isinstance(known["fallback_mode"], str):
            try:
                known["fallback_mode"] = SelectedMode(known["fallback_mode"])
            except ValueError:
                known["fallback_mode"] = None

        # Parse candidate_modes
        if "candidate_modes" in data and isinstance(data["candidate_modes"], list):
            known["candidate_modes"] = []
            for c in data["candidate_modes"]:
                if isinstance(c, dict):
                    try:
                        known["candidate_modes"].append(CandidateMode(
                            mode=SelectedMode(c.get("mode", "direct_answer")),
                            confidence=float(c.get("confidence", 0.5)),
                            reason=str(c.get("reason", "")),
                        ))
                    except (ValueError, TypeError):
                        pass

        # Parse state_scope
        if "state_scope" in data and isinstance(data["state_scope"], dict):
            ss = data["state_scope"]
            known["state_scope"] = ModeStateScope(
                thread_id=ss.get("thread_id"),
                session_id=ss.get("session_id"),
                task_id=ss.get("task_id"),
                workflow_id=ss.get("workflow_id"),
                rtcm_session_id=ss.get("rtcm_session_id"),
                governance_trace_id=ss.get("governance_trace_id"),
                memory_scope=ss.get("memory_scope", "session"),
            )

        # Parse result_sink
        if "result_sink" in data and isinstance(data["result_sink"], dict):
            rs = data["result_sink"]
            known["result_sink"] = ModeResultSink(
                frontend_thread=rs.get("frontend_thread", True),
                memory=rs.get("memory", False),
                asset=rs.get("asset", False),
                governance=rs.get("governance", False),
                runtime_artifact=rs.get("runtime_artifact", True),
                nightly_review=rs.get("nightly_review", False),
            )

        return cls(**{k: v for k, v in known.items() if v is not None})


# ---------------------------------------------------------------------------
# ID generator
# ---------------------------------------------------------------------------

def generate_mode_decision_id() -> str:
    return f"md-{time.time():.0f}-{__import__('uuid').uuid4().hex[:8]}"


# ---------------------------------------------------------------------------
# Keyword sets for rule-based inference
# ---------------------------------------------------------------------------

_GOVERNANCE_KEYWORDS = {
    "governance", "approval", "rollback", "sandbox", "upgrade",
    "predicted", "actual", "verification", "rootguard", "audit",
    "审批", "回滚", "治理", "沙盒", "验证", "复盘", "地基",
    "安全策略", "升级", "预测", "实际", "核实",
}

_ROUNDTABLE_KEYWORDS = {
    "roundtable", "council", "debate", "meeting",
    "多方讨论", "圆桌", "会议", "评审会", "争议",
    "架构决策", "决策评审", "技术评审",
}

_WORKFLOW_KEYWORDS = {
    "workflow", "pipeline", "recurring", "schedule",
    "multi-step", "dag", "n8n", "dify",
    "流程", "工作流", "多步骤", "自动化",
    "定时任务", "周期执行", "编排",
}

_TASK_KEYWORDS = {
    "implement", "fix", "run", "execute", "build", "test",
    "修改", "修复", "执行", "运行", "构建",
    "写代码", "开发", "调试", "测试",
}

_SEARCH_KEYWORDS = {
    "search", "research", "look up", "current", "latest",
    "调研", "搜索", "查询", "最新", "查找",
    "了解", "研究", "资料", "信息",
}

_AUTONOMOUS_KEYWORDS = {
    "keep working", "autonomous", "self improve", "monitor",
    "continue until", "自主代理", "长期执行", "自动持续",
    "不间断", "自主", "持续优化",
}

_CLARIFICATION_TRIGGERS = {
    "它", "这个", "那", "那里", "这时候",
    "it", "that", "this", "what", "how",
}


# ---------------------------------------------------------------------------
# Rule-based mode inference (no model call)
# ---------------------------------------------------------------------------

def _keyword_match(text: str, keywords: set[str]) -> bool:
    text_lower = text.lower()
    return any(kw in text_lower for kw in keywords)


def infer_candidate_modes(raw_input: str) -> list[CandidateMode]:
    """
    Infer candidate modes from raw_input using keyword heuristics.
    Returns list sorted by confidence descending.
    """
    candidates: list[tuple[SelectedMode, float, str]] = []
    text = raw_input.strip()

    # Short input → clarification
    if len(text) < 10:
        candidates.append((SelectedMode.CLARIFICATION, 0.85, "input too short"))

    # Governance keywords
    if _keyword_match(text, _GOVERNANCE_KEYWORDS):
        candidates.append((SelectedMode.GOVERNANCE_REVIEW, 0.90, "governance keyword match"))

    # Roundtable keywords
    if _keyword_match(text, _ROUNDTABLE_KEYWORDS):
        # Explicit roundtable → high confidence, no clarification needed
        candidates.append((SelectedMode.ROUNDTABLE, 0.95, "roundtable keyword match"))
    elif any(k in text.lower() for k in {"讨论", "评审", "会议", "圆桌", "council", "debate"}):
        candidates.append((SelectedMode.ROUNDTABLE, 0.70, "inferred roundtable — needs confirmation"))
        # Override: if only inferred, mark needs_clarification later

    # Autonomous agent
    if _keyword_match(text, _AUTONOMOUS_KEYWORDS):
        candidates.append((SelectedMode.AUTONOMOUS_AGENT, 0.85, "autonomous keyword match"))

    # Workflow
    if _keyword_match(text, _WORKFLOW_KEYWORDS):
        candidates.append((SelectedMode.WORKFLOW, 0.80, "workflow keyword match"))

    # Task
    if _keyword_match(text, _TASK_KEYWORDS):
        candidates.append((SelectedMode.TASK, 0.75, "task keyword match"))

    # Search
    if _keyword_match(text, _SEARCH_KEYWORDS):
        candidates.append((SelectedMode.SEARCH, 0.75, "search keyword match"))

    # Clarification triggers (代词 / ambiguous)
    if _keyword_match(text, _CLARIFICATION_TRIGGERS):
        if not any(c[0] == SelectedMode.CLARIFICATION for c in candidates):
            candidates.append((SelectedMode.CLARIFICATION, 0.65, "ambiguous pronoun detected"))

    # Direct answer fallback
    if not candidates:
        candidates.append((SelectedMode.DIRECT_ANSWER, 0.50, "default fallback"))

    # Sort by confidence descending
    candidates.sort(key=lambda x: x[1], reverse=True)

    return [
        CandidateMode(mode=mode, confidence=conf, reason=reason)
        for mode, conf, reason in candidates
    ]


# ---------------------------------------------------------------------------
# Priority rules — from R240-2 ModePriorityRules.json
# ---------------------------------------------------------------------------

def apply_mode_priority_rules(
    candidates: list[CandidateMode],
    raw_input: str | None = None,
) -> tuple[SelectedMode, str, bool]:
    """
    Apply R240-2 priority rules to select the final mode.

    Returns (selected_mode, priority_rule_applied, needs_clarification).
    """
    if not candidates:
        return SelectedMode.DIRECT_ANSWER, "no_candidates", False

    # Priority order from R240-2 (highest to lowest):
    # governance_review > clarification > roundtable >
    # autonomous_agent > workflow > task > search > direct_answer > mixed_mode
    _PRIORITY_ORDER = [
        SelectedMode.GOVERNANCE_REVIEW,
        SelectedMode.CLARIFICATION,
        SelectedMode.ROUNDTABLE,
        SelectedMode.AUTONOMOUS_AGENT,
        SelectedMode.WORKFLOW,
        SelectedMode.TASK,
        SelectedMode.SEARCH,
        SelectedMode.DIRECT_ANSWER,
        SelectedMode.MIXED_MODE,
    ]

    # Check if top mode has sufficient margin over second
    top = candidates[0]
    second_conf = candidates[1].confidence if len(candidates) > 1 else 0.0

    needs_clarification = False
    rule_applied = "top_candidate"

    # Rule: governance_review always wins
    if top.mode == SelectedMode.GOVERNANCE_REVIEW:
        rule_applied = "governance_over_ordinary_execution"
        needs_clarification = False

    # Rule: clarification for low confidence or short margin
    elif top.confidence < 0.65:
        needs_clarification = True
        rule_applied = "clarification_before_execution"

    elif len(candidates) > 1 and (top.confidence - second_conf) < 0.15:
        # Low margin → clarification
        needs_clarification = True
        rule_applied = "low_margin_clarification"

    # Rule: inferred roundtable needs confirmation
    elif top.mode == SelectedMode.ROUNDTABLE:
        if "roundtable" not in (raw_input or "").lower():
            # Only inferred, not explicit → needs clarification
            needs_clarification = True
            rule_applied = "suggested_roundtable_requires_confirmation"
        else:
            rule_applied = "explicit_roundtable"

    # Rule: short input → clarification
    elif raw_input and len(raw_input.strip()) < 10:
        needs_clarification = True
        rule_applied = "short_input_clarification"

    # Otherwise top candidate wins
    return top.mode, rule_applied, needs_clarification


# ---------------------------------------------------------------------------
# Core entry point
# ---------------------------------------------------------------------------

def ensure_mode_decision(
    payload: dict[str, Any] | None,
    context_id: str | None = None,
    request_id: str | None = None,
    source_system: str = "gateway",
) -> ModeDecision:
    """
    Extract existing or generate new ModeDecision from payload.

    If payload already contains a valid mode_decision dict / ModeDecision,
    it is validated and returned (not overwritten).

    R240-5 constraint: do NOT overwrite existing valid ModeDecision.
    """
    if payload is None:
        payload = {}

    # Case 1: existing mode_decision
    existing = payload.get("mode_decision")
    if existing is not None:
        if isinstance(existing, ModeDecision):
            return existing
        if isinstance(existing, dict):
            try:
                return ModeDecision.from_dict(existing)
            except Exception:
                logger.warning("[R240-5] Invalid mode_decision in payload, regenerating")

    # Case 2: no existing — generate from rules
    raw_input = payload.get("raw_input") or payload.get("input", {}).get("messages", [{}])[-1].get("content", "") if isinstance(payload.get("input"), dict) else str(payload.get("raw_input", ""))

    # Fallback: try to get from body.input.messages
    if not raw_input and isinstance(payload.get("input"), dict):
        msgs = payload["input"].get("messages")
        if msgs and isinstance(msgs, list):
            last = msgs[-1]
            if isinstance(last, dict):
                raw_input = last.get("content", "")

    candidates = infer_candidate_modes(raw_input)
    selected_mode, priority_rule, needs_clar = apply_mode_priority_rules(candidates, raw_input)

    # Determine delegation
    delegated_to = _DELEGATION_DEFAULTS.get(selected_mode, DelegatedTo.NONE)

    # Determine result_sink defaults per mode
    result_sink = ModeResultSink()
    if selected_mode == SelectedMode.GOVERNANCE_REVIEW:
        result_sink.governance = True
        result_sink.runtime_artifact = False
    elif selected_mode == SelectedMode.ROUNDTABLE:
        result_sink.frontend_thread = True
        result_sink.governance = True
    elif selected_mode == SelectedMode.AUTONOMOUS_AGENT:
        result_sink.runtime_artifact = True
        result_sink.nightly_review = True

    decision = ModeDecision(
        mode_decision_id=generate_mode_decision_id(),
        request_id=request_id,
        context_id=context_id,
        selected_mode=selected_mode,
        candidate_modes=candidates,
        confidence=candidates[0].confidence if candidates else 0.5,
        decision_reason=candidates[0].reason if candidates else "default",
        priority_rule_applied=priority_rule,
        needs_clarification=needs_clar,
        delegated_to=delegated_to,
        fallback_mode=SelectedMode.DIRECT_ANSWER,
        allowed_tools=[],
        denied_tools=[],
        state_scope=ModeStateScope(),
        result_sink=result_sink,
        created_at=datetime.now(UTC).isoformat(),
        source_system=source_system,
    )
    return decision


def inject_mode_decision_into_context(
    context: dict[str, Any] | None,
    decision: ModeDecision,
) -> dict[str, Any]:
    """
    Inject ModeDecision into context dict (non-destructive).
    """
    if context is None:
        context = {}
    context["mode_decision"] = decision.to_dict()
    return context


def extract_mode_decision_from_context(
    context: dict[str, Any] | None,
) -> ModeDecision | None:
    """
    Extract ModeDecision from context dict (if present).
    """
    if context is None:
        return None
    raw = context.get("mode_decision")
    if raw is None:
        return None
    if isinstance(raw, ModeDecision):
        return raw
    if isinstance(raw, dict):
        try:
            return ModeDecision.from_dict(raw)
        except Exception:
            return None
    return None


def mode_decision_summary(decision: ModeDecision) -> str:
    """
    Safe log summary — masks IDs, no raw_input.
    """
    def _mask(s: str | None, chars: int = 8) -> str:
        if s is None:
            return "None"
        return f"{s[:chars]}..."
    return (
        f"mode={decision.selected_mode.value} "
        f"conf={decision.confidence:.2f} "
        f"delegated={decision.delegated_to.value} "
        f"needs_clar={decision.needs_clarification} "
        f"md_id={_mask(decision.mode_decision_id)} "
        f"ctx_id={_mask(decision.context_id)}"
    )
